[test]
preload = ["./test/register-dom.ts", "./test/setup.ts"]
coverageSkipTestFiles = true
coverageThreshold = { lines = 0.25, functions = 0.25, statements = 0.25 }
coverageReporter = ["text", "lcov"]
coverageDir = "coverage"
coveragePathIgnorePatterns = [
  "**/*.d.ts",
  ".next/**",
  "node_modules/**",
  "test/**",
]
